name: Deploy to GitHub Pages (Complete Fix)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          # Make sure vite is installed globally
          npm install -g vite

      # Debug node version and environment
      - name: Debug Environment
        run: |
          node --version
          npm --version
          echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
          
      # Alternative build process
      - name: Build Project (Alternative Method)
        run: |
          echo "Creating minimal dist directory with index.html"
          mkdir -p dist
          
          # Copy original index file first as a fallback
          cp client/index.html dist/index.html
          
          # Create a simple router script
          cat > dist/hash-router.js << 'EOF'
          // Simple router for GitHub Pages
          document.addEventListener('DOMContentLoaded', function() {
            // Handle navigation
            document.body.addEventListener('click', function(e) {
              let target = e.target;
              while (target && target.tagName !== 'A') {
                target = target.parentElement;
                if (!target) return;
              }
              
              if (target && target.hostname === window.location.hostname) {
                e.preventDefault();
                const href = target.getAttribute('href');
                
                if (href.startsWith('#')) {
                  const element = document.getElementById(href.substring(1));
                  if (element) element.scrollIntoView({ behavior: 'smooth' });
                } else {
                  window.location.href = href;
                }
              }
            });
          });
          EOF
          
          # Try regular build again with flags
          echo "Attempting regular build with flags..."
          NODE_OPTIONS=--openssl-legacy-provider npm run build || echo "Regular build failed, using static files instead"
          
      # Prepare files regardless of build success
      - name: Prepare for GitHub Pages
        run: |
          echo "Preparing files for GitHub Pages..."
          
          # Copy special files for GitHub Pages
          cp client/public/404.html dist/ || echo "Warning: Could not copy 404.html"
          cp client/public/index-ghpages.html dist/ || echo "Warning: Could not copy index-ghpages.html"
          
          # Create .nojekyll file to prevent Jekyll processing
          touch dist/.nojekyll
          
          # Copy assets if they exist
          if [ -d "client/public" ]; then
            echo "Copying all public assets..."
            cp -r client/public/* dist/ || echo "Warning: Error copying public assets"
          fi
          
          # Create minimal index.html if it doesn't exist
          if [ ! -f "dist/index.html" ] || [ ! -s "dist/index.html" ]; then
            echo "Checking for static site version..."
            
            # If we have a static site HTML file, use that
            if [ -f "client/public/static-site.html" ]; then
              echo "Using static-site.html as index.html..."
              cp client/public/static-site.html dist/index.html
            else
              echo "Creating emergency redirect index.html..."
              cat > dist/index.html << 'EOF'
              <!DOCTYPE html>
              <html>
              <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>AkhileshCab - Varanasi's Reliable Cab Service</title>
                <meta http-equiv="refresh" content="0;url=https://aloksri2204.github.io/Cab_Akhilesh/index-ghpages.html">
              </head>
              <body>
                <h1>Redirecting to AkhileshCab...</h1>
                <p>If you are not redirected automatically, <a href="index-ghpages.html">click here</a>.</p>
              </body>
              </html>
              EOF
            fi
          fi
          
          # Inject router script if index.html exists and doesn't already have it
          if [ -f "dist/index.html" ]; then
            echo "Injecting router script..."
            if ! grep -q "hash-router.js" dist/index.html; then
              sed -i -e '/<\/head>/i <script src="./hash-router.js"></script>' dist/index.html || echo "Warning: Could not inject script"
            fi
          fi
          
          # List what we have in dist
          echo "Contents of dist directory:"
          ls -la dist/

      # Deploy regardless of build result
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: false # Don't remove files - just in case